import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const imageWidth = width * 0.9;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  mangaHeader: {
    padding: 16,
    backgroundColor: '#f5f5f5',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  mangaTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
    color: '#333',
  },
  startDialogue: {
    fontSize: 16,
    fontStyle: 'italic',
    textAlign: 'center',
    color: '#666',
  },
  imageContainer: {
    position: 'relative',
    margin: 8,
    alignItems: 'center',
  },
  image: {
    width: imageWidth,
    height: undefined,
    aspectRatio: 1,
    borderRadius: 8,
  },
  imageText: {
    position: 'absolute',
    bottom: 8,
    width: '90%',
    textAlign: 'center',
    fontSize: 14,
    color: '#fff',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  dialogueContainer: {
    padding: 16,
    backgroundColor: '#f8f8f8',
    margin: 8,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  japanese: {
    fontSize: 18,
    marginBottom: 4,
    fontWeight: 'bold',
    color: '#333',
  },
  romanji: {
    fontSize: 16,
    fontStyle: 'italic',
    marginBottom: 4,
    color: '#666',
  },
  translation: {
    fontSize: 14,
    color: '#888',
  },
  questionContainer: {
    padding: 16,
    backgroundColor: '#eef2ff',
    margin: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#cce',
  },
  questionText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#333',
  },
  answerContainer: {
    padding: 12,
    backgroundColor: 'white',
    marginVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  answerText: {
    fontSize: 16,
  },
  nextButton: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#007AFF',
    borderRadius: 8,
    alignSelf: 'center',
  },
  nextButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  dialogueContainer: {
    padding: 16,
    backgroundColor: '#f8f8f8',
    margin: 8,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  dialogueTextContainer: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  dialogueText: {
    fontSize: 18,
    textAlign: 'center',
    color: '#333',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 10,
  },
  typeToggleButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  toggleButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  answerContainer: {
    marginTop: 10,
    padding: 12,
    backgroundColor: '#e6f2ff',
    borderRadius: 6,
  },
  translation: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
  },
});
